source "https://rubygems.org"

gem "jekyll", "~> 3.9.3"
gem "github-pages", "~> 228"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-sitemap", "~> 1.3"
gem "jekyll-gist", "~> 1.5"
gem "jekyll-feed", "~> 0.12"
gem "jekyll-data", "~> 1.1"
gem "jemoji", "~> 0.11"
gem "typewrite", "~> 1.1"
gem "webrick", "~> 1.7.0"
gem "bundler", "~> 2.0"
gem "rake", "~> 13.0"
gem "html-proofer", "~> 3.15"